### PR TITLE
allow js files to also be shown

### PR DESCRIPTION
**Pull request by nmccready**
screen shot 2015-11-23 at 4 23 05 pm

Does this for all files if `options. generatedFile` is truthy.

References isue #9

### CODE REVIEW

**Comment by jnordberg** [comment]
Hmm... what is this supposed to do? :) AFAIK 'generatedFile' just sets the source map 'file' property

**Comment by nmccready** [comment]
So I am wondering if you did not already take care of this issue. I reverted my changes and I am still seeing the original *.js files now. Did you already add this in?

**Comment by nmccready** [comment]
Otherwise I am having a hell of ta time figuring out how to blow the browserify cache or wherever stuff is stored. I am reverting to 1.2.0 just to see if I only see coffee files in sourcemaps.

**Comment by nmccready** [comment]
Yeah you already fixed and have what I need. Sorry for all the confusion.  Anyway which commit did you start adding in the *.js files mapped to the *coffee files. Its what #9 was all about originally. So that is totally closed now.

**Comment by nmccready** [comment]
Anyway you some people might want to only see *.coffee files like it was so however you turned that on/off should be flexible. But the way you have it on master right now is what I need thank you. But for traceability purposes commenting the commit that solved #9 would help.

**Comment by jnordberg** [comment]
Ah ok I understand what you where after now, it was added with the fix for #29 (still not published on npm)

I think you misunderstand what was asked for in #9, the guy wanted to write the generated js to disk - bypassing the browserify pipeline - so he could require them directly...

**Comment by nmccready** [comment]
Is there a way to limit the sourcemaps to just generated individual .js files? I am tired of debugging the CoffeeScript in chrome as it is buggy as all get out. I just want to see the JS.

**Comment by jnordberg** [comment]
Did you try disabling them by passing sourceMap: false?

**Comment by nmccready** [comment]
Yeah I just did it; but now it only shows the *.coffee.

**Comment by nmccready** [comment]
I figured it out and it is hacky as all hell but it works. I will make a PR or just use my fork.

**Pull request closed without merging**
